# Generated by Django 4.1.7 on 2023-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='commentaire',
            field=models.TextField(default='', max_length=300),
        ),
    ]
